[project]
name = "dspy-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "dspy>=2.6.17",
    "requests>=2.32.3",
]
